# Generated by Django 3.0.3 on 2020-02-09 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.CharField(default='.txt', max_length=5),
            preserve_default=False,
        ),
    ]
