# Generated by Django 2.1.7 on 2020-03-01 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0003_auto_20200301_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
