# Generated by Django 2.1.7 on 2020-03-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('searchapp', '0004_auto_20200301_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='automatic_tags',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='path',
            field=models.FilePathField(null=True, verbose_name='File Path'),
        ),
        migrations.AlterField(
            model_name='file',
            name='type',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='user_tags',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
